# Generated by Django 3.2.25 on 2025-12-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondhand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
