# Generated by Django 3.2.25 on 2025-12-08 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondhand', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待确认'), (1, '已确认'), (2, '已完成'), (3, '已取消')], default=0, verbose_name='交易状态')),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='secondhand.product', verbose_name='交易商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.IntegerField(choices=[(0, '买家评价卖家'), (1, '卖家评价买家')], verbose_name='评价类型')),
                ('content', models.TextField(blank=True, verbose_name='评价内容')),
                ('rating', models.IntegerField(verbose_name='评分（1-5）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='secondhand.transaction', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '交易评价',
                'verbose_name_plural': '交易评价',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'reviewer', 'reviewed')},
            },
        ),
    ]
