# Generated by Django 3.2.25 on 2025-12-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已接单'), (3, '配送中'), (4, '已完成'), (5, '已取消')], verbose_name='状态')),
                ('status_display', models.CharField(max_length=50, verbose_name='状态名称')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='foodorder.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单状态历史',
                'verbose_name_plural': '订单状态历史',
                'ordering': ['change_time'],
            },
        ),
    ]
